### ISSUE TITLE
MQTT 401: Unauthorized

### ISSUE THREAD

**Issue by Eric9453** [yajrendrag/Home-Assistant-Config#3]
Hi, would you  please help me to fix this problem?
I really enjoy your MQTT project. Thank you.

M=./2020Y11M24D08H/31M00S.mp4
HTTP/1.0 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Content-Length: 17
Date: Tue, 24 Nov 2020 08:32:04 GMT
Server: Python/3.9 aiohttp/3.6.2

401: Unauthorized

**Comment by yajrendrag** [comment]
sorry, i stopped using the Yi cameras a year or so ago for other reasons, so not sure if something changed in what i documented originally or if this is unrelated to the Yi..

**Comment by Eric9453** [comment]
Got, thanks for you reply~
I find the other way to achieve motion notice by mqtt.
Your MQTT project did inspired me very much.
